🐛 為了避開與 ffpyplayer 的衝突，故將 pygame 移至函式內實作延遲載入
RuntimeError: Dynamic linking causes SDL downgrade! (compiled with version 2.28.4, linked to 2.26.4)